/*
 * Bison grammar for the simplified “P‑de‑Prova” language.
 *
 * Thi#include <stdio.h>
#define N 20

float notas[N];
int a, b, i;

void limpeza() {
    for (i = 0; i < N; i++) {
        notas[i] = 0;
    }
}

int main() {
    limpeza();
    a = 10;
    b = a * 2;
    return 1;
}
s grammar accepts programs with the following structure:
 *   • Any number of include directives (e.g. #include <stdio.h>)
 *   • Any number of constant definitions (e.g. #define N 20)
 *   • Any number of variable declarations. Variables may be simple or array
 *     declarations and can be of type int, float or char. Arrays must have
 *     a constant integer size.
 *   • Any number of function declarations. Functions are always declared
 *     with the keyword “void”, take no parameters and contain a block of
 *     statements. Within a function the allowed statements are assignments,
 *     function calls, return statements, nested blocks and for‑loops.
 *   • A single main function of the form “int main() { … }”.  Inside main
 *     only assignments, function calls and for‑loops are permitted.
 *   • Assignments support simple arithmetic expressions with at most one
 *     binary operator (two operands). Each operand may be an integer
 *     constant or a variable (optionally indexing into an array).
 *   • For‑loops follow the C syntax “for (init; condition; increment) { … }”
 *     where the increment may be a simple assignment or an increment/decrement
 *     operator (e.g. i++). The loop condition may consist of one or two
 *     relational expressions joined with logical AND (&&) or OR (||).
 *
 * On successful parsing the program prints “Programa aceito.” to stdout;
 * syntax errors are reported via yyerror().
 */

%{
#include <stdio.h>
#include <stdlib.h>

/* Forward declaration of yylex() generated by Flex. */
int yylex(void);
void yyerror(const char *s);

/* The semantic value type used by Bison.  The union allows both integer
 * literals and identifiers to be stored in the yylval variable returned
 * from the scanner.  Identifiers are stored as dynamically allocated
 * strings and must be freed by the caller if necessary.  For this
 * exercise we only need to compare tokens, so no cleanup is performed. */
%}

%union {
    int intVal;      /* integer constants */
    char *strVal;    /* identifiers */
}

/* Token declarations.  Tokens with associated values specify the type
 * contained in the union above.  For example, NUMBER has an integer
 * semantic value and IDENTIFIER has a string value. */

%token <intVal> NUMBER
%token <strVal> IDENTIFIER

/* Basic type keywords */
%token T_VOID T_INT T_FLOAT T_CHAR

/* Keywords for control and other constructs */
%token T_FOR T_RETURN T_MAIN

/* Preprocessor directives */
%token DEFINE INCLUDE

/* Logical and relational operators */
%token AND_OP OR_OP
%token EQ_OP NE_OP LE_OP GE_OP
%token INC_OP DEC_OP

/* Character tokens such as '+', '-', '*' and '/' do not need explicit
 * token declarations as Bison treats single characters returned by the
 * scanner as their own tokens.  However relational operators consisting
 * of two characters (<=, >=, ==, !=) are declared above. */

/* Precedence and associativity.  Although the grammar restricts
 * expressions to at most one binary operator, precedence is specified
 * here for completeness and to resolve potential ambiguities in
 * relational expressions. */
%left OR_OP
%left AND_OP
%nonassoc EQ_OP NE_OP
%nonassoc '<' '>' LE_OP GE_OP
%left '+' '-'
%left '*' '/'

%expect 1

%%

/* Top level nonterminal.  A complete program consists of optional
 * include and define sections followed by declarations, any number of
 * void functions, and finally a single main function. */
program
    : includes defines declarations functions main_func
    ;

/* Zero or more include directives.  Each INCLUDE token corresponds to
 * an entire line beginning with ‘#include’ and is returned by the
 * scanner.  The header name is not used by the grammar. */
includes
    : /* empty */
    | includes include_stmt
    ;

include_stmt
    : INCLUDE
    ;

/* Zero or more constant definitions.  A DEFINE token is followed by
 * an identifier and an integer literal. */
defines
    : /* empty */
    | defines define_stmt
    ;

define_stmt
    : DEFINE IDENTIFIER NUMBER
    ;

/* Zero or more variable declarations.  Each declaration starts with a
 * type and contains a comma‑separated list of variables.  Array
 * declarations specify a constant size. */
declarations
    : /* empty */
    | declarations declaration
    ;

declaration
    : type varlist ';'
    ;

type
    : T_INT
    | T_FLOAT
    | T_CHAR
    ;

varlist
    : varlist ',' var_decl
    | var_decl
    ;

var_decl
    : IDENTIFIER
    | IDENTIFIER '[' NUMBER ']'
    /* Permit array sizes to be defined by constants (identifiers) as well */
    | IDENTIFIER '[' IDENTIFIER ']'
    ;

/* Zero or more function definitions.  Functions are declared with
 * ‘void’ and take no parameters.  The body consists of a block of
 * statements. */
functions
    : /* empty */
    | functions function
    ;

function
    : T_VOID IDENTIFIER '(' ')' block
    ;

/* A single main function.  The specification requires exactly one
 * main() defined as returning int. */
main_func
    : T_INT T_MAIN '(' ')' block
    ;

/* Blocks of statements delimited by braces.  Blocks may be nested. */
block
    : '{' statements '}'
    ;

/* Zero or more statements within a block. */
statements
    : /* empty */
    | statements statement
    ;

/* A statement may be an assignment, a function call, a return statement,
 * a for‑loop, or a nested block.  Assignments and function calls are
 * terminated by semicolons. */
statement
    : assignment ';'
    | function_call ';'
    | return_stmt ';'
    | for_loop
    | block
    ;

/* Assignment: a variable (possibly indexed) followed by ‘=’ and an
 * expression.  The grammar restricts expressions to at most one binary
 * operator. */
assignment
    : var '=' expr
    ;

/* Variable usage in assignments and expressions.  Both simple
 * identifiers and array indexing are supported. */
var
    : IDENTIFIER
    | IDENTIFIER '[' expr ']'
    ;

/* Function call: identifier followed by empty parentheses.  Functions
 * have no parameters in this language. */
function_call
    : IDENTIFIER '(' ')'
    ;

/* Return statement: the return keyword followed by an expression.
 * Although functions are void, the specification example shows
 * ‘return 1;’, so an expression is permitted here. */
return_stmt
    : T_RETURN expr
    ;

/* For‑loop.  The loop has the form: for (init; condition; increment) block
 * where both the condition and increment sections are optional. */
for_loop
    : T_FOR '(' assignment ';' condition_opt ';' increment_opt ')' block
    ;

/* Optional condition.  A missing condition is treated as true. */
condition_opt
    : /* empty */
    | condition
    ;

/* A simple or compound loop condition.  Two relational expressions may
 * be combined using logical AND or OR. */
condition
    : expr rel_op expr
    | condition logic_op expr rel_op expr
    ;

rel_op
    : '<'
    | '>'
    | LE_OP
    | GE_OP
    | EQ_OP
    | NE_OP
    ;

logic_op
    : AND_OP
    | OR_OP
    ;

/* Optional increment.  The increment can either be a full assignment
 * expression or a variable with an increment/decrement operator. */
increment_opt
    : /* empty */
    | increment
    ;

increment
    : assignment
    | var INC_OP
    | var DEC_OP
    ;

/* Arithmetic expressions.  To satisfy the requirement that an
 * assignment contains at most two operands, an expression is either
 * a single term or a binary operation combining two terms. */
expr
    : term
    | term '+' term
    | term '-' term
    | term '*' term
    | term '/' term
    ;

term
    : NUMBER
    | var
    ;

%%

/* Error reporting function called by the generated parser on syntax
 * errors.  The message from Bison is forwarded to stderr with a
 * custom prefix. */
void yyerror(const char *s) {
    fprintf(stderr, "Erro de sintaxe: %s\n", s);
}

/* Main entry point.  yyparse() returns 0 on success and non‑zero on
 * failure.  Upon successful parsing, print an acknowledgement message
 * as required. */
int main(void) {
    if (yyparse() == 0) {
        printf("Programa aceito.\n");
    }
    return 0;
}